config/routes.rb
Rails.application.routes.draw do
  resources :blogs
  devise_for :users
  root 'top#index'
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  devise_scope :user do
    get '/log_out' => 'devise/sessions#destroy'
  end
end

app/models/blog.rb
class Blog < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  add_flash_types :success, :info, :warning, :danger
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTemplate</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= nav_bar fixed: :top, brand: "Rails4.2.3 Template" do %>
      <%= menu_group do %>
        <%= menu_item "Link1",  root_path %>
        <%= menu_item "Link2", root_path %>
        <%= menu_item "Link3", root_path %>
      <% end %>
      <%= menu_group pull: :right do %>
        <% if current_user %>
          <%= menu_item "ログアウト", log_out_path %>
        <% else %>
          <%= menu_item "ログイン", new_user_session_path %>
          <%= menu_item "新規登録", new_user_registration_path %>
        <% end %>
      <% end %>
    <% end %>
    <% flash.each do |key, value| %>
      <% key = "info" if key == "notice" %>
      <% key = "danger"  if key == "alert" %>
      <%= content_tag :div, value, class: "alert alert-#{key}" %>
    <% end %>
    <% unless notice.blank? %>
      <p class="notice"><%= notice %></p>
    <% end %>
    <% unless alert.blank? %>
    <p class="alert"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/top/index.html.erb
<h1>Top#index</h1>
<p>Find me in app/views/top/index.html.erb</p>